full_name = input("Full name: ")
age = int(input("Age: "))
student_id = input("Student ID: ")
city = input("City: ")
university = input("University: ")
department = input("Department: ")
email = input("Email: ")
phone = input("Phone number: ")
favorite_language = input("Favorite programming language: ")
programming_goal = input("Programming goal: ")

print()
print(f"Name:                 {full_name}")
print(f"Student ID:           {student_id}")
print(f"Age:                  {age}")
print(f"City:                 {city}")
print(f"University:           {university}")
print(f"Department:           {department}")
print(f"Email:                {email}")
print(f"Phone:                {phone}")
print(f"Favorite Language:    {favorite_language}")
print(f"Programming Goal:     {programming_goal}")