student_name = input("Student name: ")
student_id = input("Student ID: ")
department = input("Department: ")
year = input("Year: ")
university = input("University: ")
phone = input("Phone number: ")

print()
print(f"Name: {student_name}")
print(f"ID: {student_id}")
print(f"Department: {department}")
print(f"Year: {year}")
print(f"University: {university}")
print(f"Phone: {phone}")